"use client";
import { useEffect, useMemo, useState } from "react";
import { Building2, Plus, X } from "lucide-react";
import { Sidebar } from "@/components/layout/sidebar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { fetchAssets, type Asset } from "@/lib/assets/google-sheets";
import { changeAreaStatus, changeBranchStatus, fetchAreas, fetchBranches, saveArea, saveBranch, type Area, type Branch } from "@/lib/catalogs/branches";
const EMPTY = { idSucursal: "", codigo: "", nombre: "", direccion: "", ciudad: "", estadoRegion: "", responsable: "", telefono: "", estado: "Activo" };
const normalized = (value: string) => value.trim().toLocaleLowerCase();
const isInactive = (value: string) => ["inactivo", "inactiva"].includes(normalized(value));
const statusLabel = (value: string) => isInactive(value) ? "Inactiva" : "Activa";
export default function BranchesClient() {
 const [branches,setBranches]=useState<Branch[]>([]),[areas,setAreas]=useState<Area[]>([]),[assets,setAssets]=useState<Asset[]>([]),[editing,setEditing]=useState<Branch|null>(null),[areaBranch,setAreaBranch]=useState<Branch|null>(null),[areaName,setAreaName]=useState(""),[error,setError]=useState<string|null>(null);
 async function load(){ const [b,a,x]=await Promise.all([fetchBranches(),fetchAreas(),fetchAssets()]);setBranches(b);setAreas(a);setAssets(x); }
 useEffect(()=>{load().catch(()=>setError("No se pudo cargar el catálogo."));},[]);
 const cards=useMemo(()=>branches.map(b=>{
   const equipment=assets.filter(asset=>normalized(asset.sucursal)===normalized(b.nombre));
   const branchAreas=areas.filter(area=>area.idSucursal===b.idSucursal).filter((area,index,list)=>list.findIndex(candidate=>normalized(candidate.nombre)===normalized(area.nombre))===index);
   const known=new Set(branchAreas.map(area=>normalized(area.nombre)));
   equipment.forEach(asset=>{
     if(!asset.area.trim()||known.has(normalized(asset.area)))return;
     known.add(normalized(asset.area));
     branchAreas.push({idArea:`existing-${b.idSucursal}-${asset.area}`,idSucursal:b.idSucursal,nombre:asset.area.trim(),estado:"Activo"});
   });
   branchAreas.sort((left,right)=>left.nombre.localeCompare(right.nombre,"es"));
   return {...b,equipment,areas:branchAreas};
 }),[branches,areas,assets]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!editing)return;try{setError(null);await saveBranch({...editing,estado:isInactive(editing.estado)?"Inactivo":"Activo"});setEditing(null);await load();}catch(x){setError(x instanceof Error?x.message:"No se pudo guardar.");}}
 async function addArea(e:React.FormEvent){e.preventDefault();if(!areaBranch||!areaName.trim())return;try{setError(null);await saveArea({idSucursal:areaBranch.idSucursal,nombre:areaName,estado:"Activo"});setAreaName("");setAreaBranch(null);await load();}catch(x){setError(x instanceof Error?x.message:"No se pudo guardar.");}}
 async function toggleBranch(branch:Branch){const next=isInactive(branch.estado)?"Activo":"Inactivo";if(next==="Inactivo"&&!window.confirm(`¿Inactivar la sucursal ${branch.nombre}?`))return;try{setError(null);await changeBranchStatus(branch.idSucursal,next);await load();}catch(x){setError(x instanceof Error?x.message:"No se pudo cambiar el estado.");}}
 async function toggleArea(area:Area){const next=isInactive(area.estado)?"Activo":"Inactivo";if(next==="Inactivo"&&!window.confirm(`¿Inactivar el área ${area.nombre}?`))return;try{setError(null);await changeAreaStatus(area.idArea,next);await load();}catch(x){setError(x instanceof Error?x.message:"No se pudo cambiar el estado del área.");}}
 async function registerDetectedArea(branch:Branch,area:Area){if(!window.confirm(`¿Registrar ${area.nombre} como área oficial de ${branch.nombre}?`))return;try{setError(null);await saveArea({idSucursal:branch.idSucursal,nombre:area.nombre,estado:"Activo"});await load();}catch(x){setError(x instanceof Error?x.message:"No se pudo registrar el área.");}}
 return <main className="min-h-screen md:flex"><Sidebar/><section className="flex-1 p-6 lg:p-8"><header className="flex items-center justify-between"><div><h2 className="text-4xl font-black">Sucursales y áreas</h2><p className="mt-2 text-muted-foreground">Catálogo institucional y equipos asignados.</p></div><button onClick={()=>setEditing({...EMPTY})} className="inline-flex items-center gap-2 rounded-2xl bg-primary px-5 py-3 font-semibold text-primary-foreground"><Plus/>Nueva sucursal</button></header>{error?<p className="mt-5 rounded-xl bg-red-500/15 p-3 text-red-200">{error}</p>:null}<div className="mt-7 grid gap-5 xl:grid-cols-2">{cards.map((b,branchIndex)=><Card key={`${b.idSucursal || b.codigo || b.nombre}-${branchIndex}`} className="bg-white/[0.04]"><CardHeader><div className="flex justify-between"><div><CardTitle>{b.nombre}</CardTitle><p className="text-sm text-primary">{b.codigo} · {statusLabel(b.estado)}</p></div><Building2 className="text-primary"/></div></CardHeader><CardContent><p className="text-sm text-muted-foreground">{b.direccion} · {b.ciudad} · {b.estadoRegion}</p><div className="mt-4 flex gap-3"><span className="rounded-xl bg-primary/15 px-3 py-2 text-sm">{b.equipment.length} equipos</span><span className="rounded-xl bg-white/10 px-3 py-2 text-sm">{b.areas.length} áreas</span></div><div className="mt-4 flex flex-wrap gap-2">{b.areas.map((a,areaIndex)=>{const pending=a.idArea.startsWith("existing-");return <button type="button" onClick={()=>pending?registerDetectedArea(b,a):toggleArea(a)} key={`${a.idArea || a.nombre}-${areaIndex}`} title={pending?"Registrar esta área en el catálogo":isInactive(a.estado)?"Activar área":"Inactivar área"} className={`rounded-full border px-3 py-1 text-xs ${pending?"border-amber-400/40 bg-amber-400/10 text-amber-100":isInactive(a.estado)?"border-red-400/30 text-red-200 opacity-70":"border-white/10"}`}>{a.nombre} · {pending?"Pendiente de registrar":statusLabel(a.estado)}</button>})}</div><div className="mt-5 flex flex-wrap gap-2"><button className="nav-button" onClick={()=>setEditing(b)}>Editar</button><button className="nav-button" onClick={()=>setAreaBranch(b)} disabled={isInactive(b.estado)}>Agregar área</button><button className="nav-button" onClick={()=>toggleBranch(b)}>{isInactive(b.estado)?"Activar sucursal":"Inactivar sucursal"}</button></div>{b.equipment.length?<details className="mt-4"><summary className="cursor-pointer text-sm text-primary">Ver equipos</summary><ul className="mt-2 space-y-1 text-sm">{b.equipment.map((a,equipmentIndex)=><li key={`${a.codigo || a.nombre}-${equipmentIndex}`}>{a.codigo} · {a.nombre} · {a.area}</li>)}</ul></details>:null}</CardContent></Card>)}</div>
 {editing?<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/80 p-4"><form onSubmit={submit} className="mx-auto mt-8 max-w-2xl rounded-3xl bg-slate-900 p-6"><div className="flex justify-between"><h3 className="text-2xl font-bold">Sucursal</h3><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Código<input className="field mt-1 cursor-not-allowed opacity-70" value={editing.codigo || "Se genera con el nombre"} disabled/></label>{([['nombre','Nombre'],['direccion','Dirección'],['ciudad','Ciudad'],['estadoRegion','Estado/Provincia'],['responsable','Responsable'],['telefono','Teléfono']] as [keyof Branch,string][]).map(([k,l])=><label key={k} className="text-sm">{l}<input className="field mt-1" value={editing[k]} onChange={e=>setEditing({...editing,[k]:e.target.value})}/></label>)}</div><p className="mt-4 text-sm text-muted-foreground">El estado se administra desde el botón de la tarjeta para aplicar las validaciones de seguridad.</p><div className="mt-6 flex justify-end"><button className="rounded-xl bg-primary px-5 py-2 font-semibold text-primary-foreground">Guardar</button></div></form></div>:null}
 {areaBranch?<div className="fixed inset-0 z-50 bg-slate-950/80 p-4"><form onSubmit={addArea} className="mx-auto mt-20 max-w-lg rounded-3xl bg-slate-900 p-6"><h3 className="text-xl font-bold">Nueva área · {areaBranch.nombre}</h3><input autoFocus className="field mt-5" placeholder="Nombre del área" value={areaName} onChange={e=>setAreaName(e.target.value)}/><div className="mt-5 flex justify-end gap-2"><button type="button" className="nav-button" onClick={()=>setAreaBranch(null)}>Cancelar</button><button className="rounded-xl bg-primary px-5 py-2 font-semibold text-primary-foreground">Guardar</button></div></form></div>:null}</section></main>;
}
